language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 - sudo apt-get install libzmq3-dev
 - pip install pep8

script:
 - python setup.py install
 - ./run_tests
